gerrit/hooks: convert lockfile to flock
* lockfile is part of procmail which no longer exists
  in alpine due to security issues.
* flock is a little more generic

diff --git a/data/gerrit/hooks/ref-updated b/data/gerrit/hooks/ref-updated
--- a/data/gerrit/hooks/ref-updated
+++ b/data/gerrit/hooks/ref-updated
@@ -67,37 +67,24 @@ echo "Obtaining lock..."
 
 lockfile=$GIT_DIR/receive.lock
 
-with_lock_unlock_if_held() {
-	if [[ "$with_lock_has_lock" -eq 1 ]] ; then
-		rm -f "$lockfile"
-	fi
-}
-
 # grab lockfile to protect against concurrent post-receive
 # hooks getting confused with the order of hrevs
-with_lock_has_lock=0
-trap with_lock_unlock_if_held INT TERM EXIT
-lockfile -1 -r 30 "$lockfile"
-if [ $? -ne 0 ] ; then
-	exit $?
-fi
-with_lock_has_lock=1
+(
+  flock -w 30 --verbose 9 || exit 1
+  export GIT_DIR
+  cd "$GIT_DIR"
+  echo "-------------receive-notify--------------"
+  # create hrev-tags and send e-mail & cia notifications
+  echo "$OLDREV $NEWREV $REFNAME" | USER="$UPLOADER_USERNAME" USER_EMAIL="$UPLOADER_EMAIL" $GERRIT_SITE/hooks/receive-notify.pl
 
-export GIT_DIR
-cd "$GIT_DIR"
-
-echo "-------------receive-notify--------------"
-# create hrev-tags and send e-mail & cia notifications
-echo "$OLDREV $NEWREV $REFNAME" | USER="$UPLOADER_USERNAME" USER_EMAIL="$UPLOADER_EMAIL" $GERRIT_SITE/hooks/receive-notify.pl
-
-# tell buildbot about new changes
-if [ -f "$GIT_DIR/hooks/git_buildbot.py" ] ; then
-	echo "Notifying buildbot of $NEWREV @ $REFNAME"
-	echo -n "$OLDREV $NEWREV $REFNAME" | $GIT_DIR/hooks/git_buildbot.py -v
-fi
+  # tell buildbot about new changes
+  #if [ -f "$GIT_DIR/hooks/git_buildbot.py" ] ; then
+  #  echo "Notifying buildbot of $NEWREV @ $REFNAME"
+  #  echo -n "$OLDREV $NEWREV $REFNAME" | $GIT_DIR/hooks/git_buildbot.py -v
+  #fi
+) 9>$lockfile
 
 echo "Release lock..."
 
-# cleanup lockfile
+# cleanup lockfile if it exists for some reason
 rm -f "$lockfile"
-with_lock_has_lock=0
